(write(defun append-list (a)
    (function (lambda (b) (append a b)))
))
(terpri)
(write(setq uuu (append-list '(a b c))))
(terpri)
(write(funcall uuu '(1 2 3)))
(terpri)
(write(funcall uuu '(4 5 6)))